name: Matthieu Ringard
url: http://matthieuringd1.github.io
description: Data science student at Centrale Lille 

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
